# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.certificates.client .Values.certificates.secrets }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "web.name" . }}-client-certificate
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  secretName: {{ include "web.clientCertificateSecretName" . }}
  dnsNames:
    - {{ include "web.clientCertificateDNSName" . | quote }}
  usages:
    - digital signature
    - client auth
  issuerRef:
    kind: ClusterIssuer
    name: platform-service-certificate-clusterissuer
{{- end }}
