---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.name" . }}-caddy-configmap
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
  Caddyfile: |
    {
      auto_https off
      {{- if .Values.metrics }}
      {{- if .Values.metrics.http }}
      metrics
      {{- end }}
      {{- end }}
    }
    :443 {
      tls /etc/caddy/certs/tls.crt /etc/caddy/certs/tls.key
      reverse_proxy 127.0.0.1:{{ .Values.app.port }}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.name" . }}-deployment
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "web.name" . }}-container
          image: {{ .Values.images.app | quote }}
          {{- with .Values.app.env }}
          env:
            {{- range $name, $value := . }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
        - name: {{ include "web.name" . }}-caddy
          image: {{ .Values.images.caddy | quote }}
          ports:
            - containerPort: 443
            {{- if .Values.metrics }}
            {{- if .Values.metrics.http }}
            - containerPort: 2019
            {{- end }}
            {{- end }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "256Mi"
          volumeMounts:
            - name: {{ include "web.name" . }}-caddy-tls-volume
              mountPath: /etc/caddy/certs
            - name: {{ include "web.name" . }}-caddy-config-volume
              mountPath: /etc/caddy
      volumes:
        - name: {{ include "web.name" . }}-caddy-tls-volume
          secret:
            secretName: {{ include "web.name" . }}-certificate-secret
        - name: {{ include "web.name" . }}-caddy-config-volume
          configMap:
            name: {{ include "web.name" . }}-caddy-configmap
