# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0

{{- $ports := list .Values.app.port }}
{{- if kindIs "slice" .Values.app.port }}
{{- $ports = .Values.app.port }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.name" . }}-service
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: {{ if eq .Values.certificates.server "sidecar" }}8443{{ else }}{{ include "web.primaryPort" . }}{{ end }}
    {{- range $index, $port := $ports }}
    {{- if gt $index 0 }}
    - name: {{ printf "port-%v" $port | quote }}
      protocol: TCP
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
    {{- end }}
