# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0

{{- if or .Values.secrets .Values.serviceAccount.name }}
{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web.serviceAccountName" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
{{- end }}
{{- end }}
