---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.name" . }}-service
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
