# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: worker
description: Podplane background worker template chart
type: application
version: "1.0.0"
appVersion: "1.0.0"
