# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
images:
  app: "ghcr.io/podplane/hello:latest"
  envoy: "docker.io/envoyproxy/envoy:distroless-v1.37-latest"
app:
  env: {}
  port: 8080
route:
  hostname: ""
  path: /
  port: 443
serviceAccount:
  create: true
  name: ""
secrets: []
certificates:
  server: sidecar
  client: false
