# Podplane <https://podplane.dev>
# Copyright 2026 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
images:
  app: "ghcr.io/podplane/hello:latest"
  caddy: "docker.io/library/caddy:2"
app:
  env: {}
  port: 80
route:
  hostname: ""
  path: /
  port: 443
metrics:
  http: true # enables Caddy http metrics - see https://caddyserver.com/docs/metrics for more
serviceAccount:
  create: true
  name: ""
secrets: []
