# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
images:
  app: "ghcr.io/podplane/hello:latest"
  # Keep this aligned with the Envoy version selected by Envoy Gateway where
  # possible to minimize cached images. Envoy Gateway's version takes priority
  # for maximum interoperability with its managed data plane.
  envoy: "docker.io/envoyproxy/envoy:distroless-v1.39.0"
app:
  env: {}
  port: 8080
route:
  hostname: ""
  path: /
  port: 443
serviceAccount:
  create: true
  name: ""
secrets: []
certificates:
  server: sidecar
  client: false
